name: Build PSP Homebrew

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspdev:latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Compilar
        run: make

      - name: Disponibilizar o EBOOT.PBP pra download
        uses: actions/upload-artifact@v4
        with:
          name: rpg_fase1-EBOOT
          path: EBOOT.PBP
